sudo: required

language: python

services:
  - docker

before_install:
- pip install virtualenv

script:
- bash ./scripts/ci_tests.sh

after_success:
- bash ./scripts/push.sh

deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  domain: $OPENSHIFT_DOMAIN
  app: $OPENSHIFT_DOMAIN

after_deploy:
  - pip install requests
  - python tests/smoke.py https://alerted.us