sudo: required

services:
  - docker

before_install:
  - pip install virtualenv
  - docker version

script:
  - bash ./scripts/ci_tests.sh

deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  domain: $OPENSHIFT_DOMAIN
  app: $OPENSHIFT_APP

after_deploy:
  - pip install requests
  - python tests/smoke.py https://alerted.us