sudo: required

language: python

services:
  - docker

before_install:
- docker pull carlad/sinatra
- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- docker ps -a
- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

- set -e

- virtualenv ~/venv
- source ~/venv/bin/activate
- pip install -U docker-compose==1.5.2

- docker-compose up -d
- sleep 10 # Wait for DB to come up before proceeding. Can be better...

- docker-compose run db sh -c 'exec psql -h "$DB_PORT_5432_TCP_ADDR" -p "$DB_PORT_5432_TCP_PORT" -U postgres -c "CREATE EXTENSION IF NOT EXISTS POSTGIS"'

- docker-compose run web /bin/bash -c "python manage.py migrate --noinput"
- docker-compose run web /bin/bash -c "python manage.py collectstatic --noinput"

script:
- docker-compose run web /bin/bash -c "python manage.py test"

after_success:
- docker-compose stop && docker-compose rm -f

after_failure:
- docker-compose stop && docker-compose rm -f
