version: '2.0'
services:
  db:
    image: mdillon/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
      PGPASSWORD: password

  web:
    image: alerted-us-web:latest
    build: .
    volumes:
      - .:/code
    ports:
      - "8000"
    environment:
      RACK_ENV: development
      DATABASE_URL: postgis://postgres:password@db:5432/postgres
    links:
      - db
    depends_on:
      - db
    command: ./run.sh