db:
  image: mdillon/postgis
  volumes:
    - /data/postgresql/9.4/var/lib/postgresql:/var/lib/postgresql/data

redis:
  restart: always
  image: tutum/redis
  ports:
    - "6379:6379"
  environment:
    REDIS_PASS: password

web:
  build: .
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  environment:
    RACK_ENV: docker
    REDIS_ENDPOINT: redis
    REDIS_PASSWORD: password
    REDIS_PORT: 6379
    DB_PASSWORD: ""
    DB_NAME: postgres
    DB_USER: postgres
    DB_HOST: db
    DB_PORT: 5432
    DEBUG: True
  links:
    - db
    - redis