version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - setup_remote_docker
      - run: bash ./scripts/build.sh
  test:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: bash ./scripts/test.sh
  deploy_staging:
    docker:
      - image: circleci/python:2.7
    steps:
      - run: echo "Hello World"
  deploy_prod:
    docker:
      - image: circleci/python:2.7
    steps:
      - run: echo "Hello World"


workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test