version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: bash ./scripts/ci_tests.sh
  deploy_staging:
    docker:
      - image: circleci/python:2.7
    steps:
      - run: echo "Hello World"


workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test:
      - deploy_staging:
          requires:
            - test